### ISSUE TITLE
App name in App Properties needs enhancement

### ISSUE THREAD

**Issue by Sughosha** [leoxshn/posidonLauncher#14]
If I long press an app, the app name is not shown property, if the app name is long.

![20200520_110812](https://user-images.githubusercontent.com/59734562/82408923-22383880-9a5c-11ea-99da-5241ed809a8a.jpg)
_It should show **Acrobat for Samsung**_

![20200520_110733](https://user-images.githubusercontent.com/59734562/82408937-28c6b000-9a5c-11ea-86d2-4e2190f846f2.jpg)
_The icon for **settings** overlaps the app name_

Possible solutions for this would be:

- Increasing the size of the _box_ if the name is longer.
- Letting to scroll down the name

**Comment by Sughosha** [comment]
https://user-images.githubusercontent.com/59734562/82408937-28c6b000-9a5c-11ea-86d2-4e2190f846f2.jpg

Still the _App Settings_ icon is overlapping the app name.

**Comment by leoxshn** [comment]
I'll fix it

**Comment by Sughosha** [comment]
This got fixed...
![Screenshot_20200520-190940_posidon launcher](https://user-images.githubusercontent.com/59734562/82452962-73b5e700-9a9f-11ea-84f0-a8685191a0a1.jpg)



**But the problem got transferred to this**:
![Screenshot_20200520-190754_posidon launcher](https://user-images.githubusercontent.com/59734562/82453163-b4156500-9a9f-11ea-830d-24563769810c.jpg)

I think, the space you are giving for _name_ should not touch the _settings_ icon. Instead of resizing the text size, you can put margin before & keeping distance fron the _settings_ icon.
